--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-10-07 00:22:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 17076)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id integer NOT NULL,
    lastname character varying(255),
    name character varying(255)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17075)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3343 (class 0 OID 17076)
-- Dependencies: 225
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.customer (id, lastname, name) VALUES (1, 'Daugherty', 'Amos');
INSERT INTO public.customer (id, lastname, name) VALUES (2, 'Simon', 'Ursula');
INSERT INTO public.customer (id, lastname, name) VALUES (3, 'Kline', 'Burton');
INSERT INTO public.customer (id, lastname, name) VALUES (4, 'Graham', 'Kai');
INSERT INTO public.customer (id, lastname, name) VALUES (5, 'Banks', 'Chelsea');
INSERT INTO public.customer (id, lastname, name) VALUES (6, 'Morgan', 'Phyllis');
INSERT INTO public.customer (id, lastname, name) VALUES (7, 'Anthony', 'Merritt');
INSERT INTO public.customer (id, lastname, name) VALUES (8, 'Marks', 'Marah');
INSERT INTO public.customer (id, lastname, name) VALUES (9, 'Mcgowan', 'Tiger');
INSERT INTO public.customer (id, lastname, name) VALUES (10, 'Joyner', 'Winter');
INSERT INTO public.customer (id, lastname, name) VALUES (11, 'Sellers', 'Rosalyn');
INSERT INTO public.customer (id, lastname, name) VALUES (12, 'Merrill', 'Todd');
INSERT INTO public.customer (id, lastname, name) VALUES (13, 'Sellers', 'Alyssa');
INSERT INTO public.customer (id, lastname, name) VALUES (14, 'Ball', 'Kimberley');
INSERT INTO public.customer (id, lastname, name) VALUES (15, 'Sharp', 'Axel');
INSERT INTO public.customer (id, lastname, name) VALUES (16, 'Anthony', 'Rinah');
INSERT INTO public.customer (id, lastname, name) VALUES (17, 'Dotson', 'Bert');
INSERT INTO public.customer (id, lastname, name) VALUES (18, 'Norman', 'Owen');
INSERT INTO public.customer (id, lastname, name) VALUES (19, 'Robinson', 'Richard');
INSERT INTO public.customer (id, lastname, name) VALUES (20, 'Benton', 'Phyllis');


--
-- TOC entry 3349 (class 0 OID 0)
-- Dependencies: 224
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 1, false);


--
-- TOC entry 3199 (class 2606 OID 17082)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


-- Completed on 2023-10-07 00:22:16

--
-- PostgreSQL database dump complete
--

