--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-10-07 00:22:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 17084)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id integer NOT NULL,
    price numeric(19,2),
    product_name character varying(255)
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17083)
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3343 (class 0 OID 17084)
-- Dependencies: 227
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product (id, price, product_name) VALUES (1, 400.00, 'Clams - Bay');
INSERT INTO public.product (id, price, product_name) VALUES (2, 794.00, 'Ecolab - Power Fusion');
INSERT INTO public.product (id, price, product_name) VALUES (3, 541.00, 'Cheese - Shred Cheddar / Mozza');
INSERT INTO public.product (id, price, product_name) VALUES (4, 193.00, 'Devonshire Cream');
INSERT INTO public.product (id, price, product_name) VALUES (5, 248.00, 'Longos - Cheese Tortellini');
INSERT INTO public.product (id, price, product_name) VALUES (6, 965.00, 'Sauce - Soy Low Sodium - 3.87l');
INSERT INTO public.product (id, price, product_name) VALUES (7, 924.00, 'Flour - Corn, Fine');
INSERT INTO public.product (id, price, product_name) VALUES (8, 324.00, 'Tobasco Sauce');
INSERT INTO public.product (id, price, product_name) VALUES (9, 653.00, 'Cheese - St. Paulin');
INSERT INTO public.product (id, price, product_name) VALUES (10, 588.00, 'Lettuce - Arugula');
INSERT INTO public.product (id, price, product_name) VALUES (11, 612.00, 'Passion Fruit');
INSERT INTO public.product (id, price, product_name) VALUES (12, 515.00, 'Cheese Cloth');
INSERT INTO public.product (id, price, product_name) VALUES (13, 56.00, 'Pastry - Carrot Muffin - Mini');
INSERT INTO public.product (id, price, product_name) VALUES (14, 776.00, 'Asparagus - Mexican');
INSERT INTO public.product (id, price, product_name) VALUES (15, 589.00, 'Rice Pilaf, Dry,package');
INSERT INTO public.product (id, price, product_name) VALUES (16, 536.00, 'Lamb - Racks, Frenched');
INSERT INTO public.product (id, price, product_name) VALUES (17, 106.00, 'Pate - Peppercorn');
INSERT INTO public.product (id, price, product_name) VALUES (18, 378.00, 'Wine - White, Chardonnay');
INSERT INTO public.product (id, price, product_name) VALUES (19, 503.00, 'Bread Crumbs - Japanese Style');
INSERT INTO public.product (id, price, product_name) VALUES (20, 137.00, 'Trueblue - Blueberry Cranberry');
INSERT INTO public.product (id, price, product_name) VALUES (21, 479.00, 'Beets - Mini Golden');
INSERT INTO public.product (id, price, product_name) VALUES (22, 790.00, 'Roe - Lump Fish, Red');
INSERT INTO public.product (id, price, product_name) VALUES (23, 230.00, 'French Kiss Vanilla');
INSERT INTO public.product (id, price, product_name) VALUES (24, 594.00, 'Basil - Fresh');
INSERT INTO public.product (id, price, product_name) VALUES (25, 700.00, 'Extract - Raspberry');
INSERT INTO public.product (id, price, product_name) VALUES (26, 159.00, 'Extract - Raspberry');
INSERT INTO public.product (id, price, product_name) VALUES (27, 765.00, 'Cup - 3.5oz, Foam');
INSERT INTO public.product (id, price, product_name) VALUES (28, 594.00, 'Trout - Hot Smkd, Dbl Fillet');
INSERT INTO public.product (id, price, product_name) VALUES (29, 934.00, 'Juice - Orangina');
INSERT INTO public.product (id, price, product_name) VALUES (30, 940.00, 'Cheese - Perron Cheddar');
INSERT INTO public.product (id, price, product_name) VALUES (31, 809.00, 'Pork - Kidney');
INSERT INTO public.product (id, price, product_name) VALUES (32, 134.00, 'Wine - Cava Aria Estate Brut');
INSERT INTO public.product (id, price, product_name) VALUES (33, 235.00, 'Wine - Rioja Campo Viejo');
INSERT INTO public.product (id, price, product_name) VALUES (34, 753.00, 'Table Cloth 53x53 White');
INSERT INTO public.product (id, price, product_name) VALUES (35, 22.00, 'Beef - Flank Steak');
INSERT INTO public.product (id, price, product_name) VALUES (36, 476.00, 'Wine - Port Late Bottled Vintage');
INSERT INTO public.product (id, price, product_name) VALUES (37, 542.00, 'Rum - Mount Gay Eclipes');
INSERT INTO public.product (id, price, product_name) VALUES (38, 29.00, 'Guava');
INSERT INTO public.product (id, price, product_name) VALUES (39, 828.00, 'Tofu - Firm');
INSERT INTO public.product (id, price, product_name) VALUES (40, 34.00, 'Bag - Bread, White, Plain');
INSERT INTO public.product (id, price, product_name) VALUES (41, 382.00, 'Grapes - Black');
INSERT INTO public.product (id, price, product_name) VALUES (42, 312.00, 'Chicken - Base');
INSERT INTO public.product (id, price, product_name) VALUES (43, 606.00, 'Pur Source');
INSERT INTO public.product (id, price, product_name) VALUES (44, 403.00, 'Sesame Seed');
INSERT INTO public.product (id, price, product_name) VALUES (45, 671.00, 'Cod - Black Whole Fillet');
INSERT INTO public.product (id, price, product_name) VALUES (46, 109.00, 'Flour - Rye');
INSERT INTO public.product (id, price, product_name) VALUES (47, 334.00, 'Pepper - Cayenne');
INSERT INTO public.product (id, price, product_name) VALUES (48, 354.00, 'Chef Hat 25cm');
INSERT INTO public.product (id, price, product_name) VALUES (49, 404.00, 'Juice - V8, Tomato');
INSERT INTO public.product (id, price, product_name) VALUES (50, 182.00, 'Garam Marsala');


--
-- TOC entry 3349 (class 0 OID 0)
-- Dependencies: 226
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 50, true);


--
-- TOC entry 3199 (class 2606 OID 17088)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


-- Completed on 2023-10-07 00:22:46

--
-- PostgreSQL database dump complete
--

